"""changed dtype for return_amt_paid

Revision ID: 479dd8cd87e8
Revises: fb5302b8804f
Create Date: 2025-11-28 14:54:31.602015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479dd8cd87e8'
down_revision: Union[str, Sequence[str], None] = 'fb5302b8804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
