"""sec tables

Revision ID: 8d23f3ea4f40
Revises: 66a3378ca337
Create Date: 2025-11-25 12:41:15.400134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d23f3ea4f40'
down_revision: Union[str, Sequence[str], None] = '66a3378ca337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('auto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_nature', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('account_subtypetwo', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_table('closing_process',
    sa.Column('auto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=True),
    sa.Column('cust_ledger', sa.String(length=50), nullable=True),
    sa.Column('gmail', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_purchase', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('inv_name', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_sale', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('customer_name', sa.String(length=50), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('cur_status', sa.String(length=50), nullable=True),
    sa.Column('inv_name', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('sales_price', sa.Integer(), nullable=True),
    sa.Column('cost_of_goods_sold', sa.Integer(), nullable=True),
    sa.Column('bad_debts_amount', sa.Integer(), nullable=True),
    sa.Column('return_qty', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inv_name', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('auto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date_of_entry', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(length=50), nullable=True),
    sa.Column('debit_amt', sa.Integer(), nullable=True),
    sa.Column('credit_amt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=50), nullable=True),
    sa.Column('cust_ledger', sa.String(length=50), nullable=True),
    sa.Column('gmail', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    op.drop_table('journal_entries')
    op.drop_table('inventories')
    op.drop_table('inv_sales')
    op.drop_table('inv_purchases')
    op.drop_table('customers')
    op.drop_table('closing_process')
    op.drop_table('accounts')
    # ### end Alembic commands ###
