"""added date_of_entry

Revision ID: d3ac52559127
Revises: 8d23f3ea4f40
Create Date: 2025-11-26 19:20:41.259446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ac52559127'
down_revision: Union[str, Sequence[str], None] = '8d23f3ea4f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closing_process', sa.Column('date_of_entry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('closing_process', 'date_of_entry')
    # ### end Alembic commands ###
