"""added new col

Revision ID: fb5302b8804f
Revises: 27a41b6eaaab
Create Date: 2025-11-28 14:53:46.501383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5302b8804f'
down_revision: Union[str, Sequence[str], None] = '27a41b6eaaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv_sales', sa.Column('return_amt_paid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inv_sales', 'return_amt_paid')
    # ### end Alembic commands ###
